name: pull-request

on:
  pull_request:

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      # Linux deps for minilibx-linux
      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxext-dev zlib1g-dev

      # Optional: tools
      - name: Install tools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y valgrind cppcheck clang-format

      - name: Install tools (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cppcheck clang-format

      - name: Build (release)
        run: make

      - name: Build (debug)
        run: make debug

      - name: Parser tests
        run: make test_parser

      # - name: Lint (cppcheck)
      #   run: make lint_cppcheck

      - name: Memcheck (Linux / valgrind)
        if: runner.os == 'Linux'
        run: make memcheck_linux

      - name: Memcheck (macOS / leaks)
        if: runner.os == 'macOS'
        run: make memcheck_macos